server:
  port: 8099

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
